const buttons = document.querySelectorAll(".playerPick");

buttons.forEach((button) => {
  // and for each one we add a 'click' listener
  button.addEventListener("click", (e) => {
    play(button.id);
  });
});

function play(opt) {
  game(opt);
}

function computerPlay() {
  switch (Math.floor(Math.random() * 3) + 1) {
    case 1:
      return "Rock";
      break;
    case 2:
      return "Paper";
      break;
    case 3:
      return "Scissor";
      break;
    default:
      return "Fail";
  }
}

//play a round and return a string indicating who won.
//takes player decision string
//takes computer decision (generated by computerPlay() function)
function playRound(playerSelection, computerSelection) {
  if (playerSelection == null) {
    return "???";
  }
  if (playerSelection.toLowerCase() == computerSelection.toLowerCase()) {
    return "Tie!";
  } else if (
    playerSelection.toLowerCase() == "rock" &&
    computerSelection.toLowerCase() == "paper"
  ) {
    return "You Lose! Paper beats Rock.";
  } else if (
    playerSelection.toLowerCase() == "rock" &&
    computerSelection.toLowerCase() == "scissor"
  ) {
    return "You Win! Rock beats Scissor.";
  } else if (
    playerSelection.toLowerCase() == "paper" &&
    computerSelection.toLowerCase() == "rock"
  ) {
    return "You Win! Paper beats Rock.";
  } else if (
    playerSelection.toLowerCase() == "paper" &&
    computerSelection.toLowerCase() == "scissor"
  ) {
    return "You Lose! Scissor beats Paper.";
  } else if (
    playerSelection.toLowerCase() == "scissor" &&
    computerSelection.toLowerCase() == "rock"
  ) {
    return "You Lose! Rock beats Scissor.";
  } else if (
    playerSelection.toLowerCase() == "scissor" &&
    computerSelection.toLowerCase() == "paper"
  ) {
    return "You Win! Scissor beats Paper.";
  } else {
    return (
      "Something went wrong... Player Played: " +
      playerSelection +
      " ComputerPlayed: " +
      computerSelection
    );
  }
}

function game(playerChoice) {
  //Select all elements to be used/updated
  let playerWin = document.querySelector("#playerScore");
  let compWin = document.querySelector("#compScore");
  let msg = document.querySelector("#decision");
  console.log(playerWin.textContent);
  console.log(compWin.textContent);
  
  //Play round and increase score accordingly
  let decision = playRound(playerChoice, computerPlay());
  if (decision.charAt(4) == "W") {
    playerWin.textContent = Number(playerWin.textContent) + 1;
  } else if (decision.charAt(4) == "L") {
    compWin.textContent = Number(compWin.textContent) + 1;
  } else {
  }

  //Check if There Was A Real Win (First to 5)
  msg.textContent = "This Round: \n " + decision;
  if(Number(playerWin.textContent) == 5)
  {
    msg.textContent = "PLAYER WINS! " + playerWin.textContent + " - " + compWin.textContent;
    playerWin.textContent = 0;
    compWin.textContent = 0;
  }
  else if(Number(compWin.textContent) == 5)
  {
    msg.textContent = "COMPUTER WINS! " + playerWin.textContent + " - " + compWin.textContent;
    playerWin.textContent = 0;
    compWin.textContent = 0;
  }
  //Check if player or comp has 5
}
